# imagePullSecrets:
replicas: 2
# REPLACE ME
elbId:
service:
  externalTrafficPolicy: Local
  annotations:
    kubernetes.io/elb.id: "{{ .Values.elbId }}"
    kubernetes.io/elb.health-check-flag: "off"
image:
  repository: "instrumentisto/coturn"
  tag: "4.5.1.3"
  pullPolicy: IfNotPresent
replicaCount: 1
resources: { }
# Coturn specific labels
labels:
  component: coturn
ports:
  min: 49152
  max: 65535
  listening: 3478
  tlsListening: 5349

#Enable auto issuing certificates over cert-manager certificates https://cert-manager.io/docs/concepts/certificate/
certificate:
  enabled: false


config:
  auth:
    username: "turnUser"
    password: 123

  turnserver: |
    realm={{ .Values.certificate.host }}
    listening-ip=0.0.0.0
    listening-port={{ .Values.ports.listening }}
    tls-listening-port={{ .Values.ports.tlsListening }}
    min-port={{ .Values.ports.min }}
    max-port={{ .Values.ports.max }}
    log-file=stdout
    verbose
    pidfile=/var/tmp/turnserver.pid
    lt-cred-mech
    user={{ .Values.config.auth.username }}:{{ .Values.config.auth.password }}
    pkey=/tls/tls.key
    cert=/tls/tls.crt
    psql-userdb="host={{ .Values.config.externalDatabase.host }} port={{ .Values.config.externalDatabase.port }} dbname={{ .Values.config.externalDatabase.database }} user={{ .Values.config.externalDatabase.user }} password={{ .Values.config.externalDatabase.password }} connect_timeout=30"
